
-- 연습1
SELECT NAME FROM T_STUDENT WHERE HEIGHT >=180;
-- 연습2
SELECT  NAME, WEIGHT FROM T_STUDENT WHERE WEIGHT >=60 AND WEIGHT <=80;
-- 연습3
SELECT *  FROM T_STUDENT WHERE DEPTNO1 IN (101,201);
-- 연습4
SELECT NAME FROM T_STUDENT WHERE NAME LIKE '김%';
-- 연습5
SELECT NAME, GRADE, HEIGHT FROM T_STUDENT WHERE GRADE = 4 AND HEIGHT >=170;
-- 연습6 
SELECT name, GRADE, WEIGHT FROM T_STUDENT WHERE GRADE =1 OR WEIGHT >=80;
-- 연습7
SELECT NAME,GRADE, HEIGHT , WEIGHT FROM T_STUDENT WHERE GRADE = 2 AND (HEIGHT > 180 and WEIGHT > 70);
-- 연습8
SELECT NAME,GRADE, HEIGHT , WEIGHT FROM T_STUDENT WHERE GRADE =2 AND (HEIGHT > 180 or WEIGHT > 70) ;
-- 연습9
SELECT ENAME , HIREDATE FROM T_EMP  WHERE HIREDATE < '1992/01/01';
-- 연습10
SELECT NAME, BIRTHDAY, HEIGHT, WEIGHT FROM T_STUDENT WHERE GRADE =1 ORDER BY BIRTHDAY ASC ;
--연습 11
SELECT NAME 이름, HEIGHT 키 FROM T_STUDENT WHERE GRADE =1 ORDER BY NAME ASC ;
--연습 12
SELECT NAME , BIRTHDAY FROM T_EMP2 WHERE BIRTHDAY BETWEEN '1980/01/01' AND '1989/12/31';
SELECT NAME , BIRTHDAY FROM T_EMP2 WHERE '1980/01/01' <= BIRTHDAY AND BIRTHDAY <'1990/01/01';

